### ISSUE TITLE
Application doesn't start on Quest 3

### ISSUE THREAD

**Issue by Zulex** [BattleAxeVR/OK_Cloud_Streamer#1]
Hi! 

Thanks for making this available. I am having trouble getting CloudXR 4.0 to work with the official documentation so this was welcome. I am unable to make connection with the regular unity plugin, so thought I would use your client application to atleast ensure that the client is fully working and rule that out as variable.

However, I am not able to start the OK_Cloud_streamer on the Quest 3.
I deployed the 120hz APK via sidequest to my Quest 3. The application installs and I can open it. However, I see a loading circle animation for a second or two and then the application force quits. 
I am under the assumption that the 'CloudXRLaunchOptions.txt' was only there to deploy the application to the right ip (the headset). 

Am I missing any steps to make the application not force quit?

Thanks again for your work, and hope to get this working! (eye tracking for other headsets is also a warm welcome!)

**Comment by BattleAxeVR** [comment]
The IP in that text file is the local (or global) IP of the server (PC), not the client. CloudXR uses it to semi-dynamically pick the IP without it being hardcoded into the APK or requiring some kind of UI to type it in. (I've implemented that myself in a previous app, but I am waiting for chromium to be released before starting over).

Let me know if that fixes it!

**Comment by Zulex** [comment]
@BattleAxeVR Thanks for the help! I got it too work. SteamVR was crashing, however enabling the audio on the server made it work. For anyone looking at this later, see how to do that here: 

https://docs.nvidia.com/cloudxr-sdk/usr_guide/cmd_line_options.html#command-line-options

Seems like it was indeed the unity plugin which wasn't working, so I can start debugging that.
